# This is a basic workflow to help you get started with Actions

name: Deploy to AppEngine GCP

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [app_engine_node]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

#     - id: 'secrets'
#       uses: 'google-github-actions/get-secretmanager-secrets@v0'
#       with:
#         secrets: |-
#           test_token:projects/885475882644/secrets/test
          
#     - name: Create env file
#       run: |
#           touch .env
#           echo '${{ steps.secrets.outputs.token }}' >> .env

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
